channels:
- conda-forge
- gimli
- defaults
dependencies:
- backports=1.0=py36_1
- backports.functools_lru_cache=1.4=py36_1
- boost=1.65.1=py36_0
- boost-cpp=1.65.1=1
- bzip2=1.0.6=1
- ca-certificates=2017.11.5=0
- certifi=2017.11.5=py36_0
- cycler=0.10.0=py36_0
- dbus=1.10.22=0
- expat=2.2.1=0
- fontconfig=2.12.1=5
- freetype=2.7=2
- gettext=0.19.7=1
- glib=2.53.5=1
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=1
- icu=58.2=0
- jpeg=9b=2
- libffi=3.2.1=3
- libiconv=1.14=4
- libpng=1.6.28=2
- libxcb=1.12=1
- libxml2=2.9.5=1
- matplotlib=2.1.0=py36_1
- ncurses=5.9=10
- openblas=0.2.20=4
- openssl=1.0.2l=0
- pcre=8.39=0
- pip=9.0.1=py36_0
- py=1.5.2=py_0
- pyparsing=2.2.0=py36_0
- pyqt=5.6.0=py36_4
- pytest=3.2.5=py36_0
- python=3.6.3=1
- qt=5.6.2=6
- numpy=1.13.3=py36ha12f23b_0
- scipy=1.0.0=py36hbf646e7_0
- pygimli=v1.0.4=py36_1

